parameters:
#    walkeros_user.example.class: Walkeros\UserBundle\Example

services:
#    walkeros_user.example:
#        class: %walkeros_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
